Exception
-
Is built in Object and it is created during runtime
Program abnormal terminates

Rule
-
Handle Rule
	try{
		//code
	}
	catch ( TYPE variable ) {
		// handle the exception
	}
	finally {
		//statements
	}
Declare rule